//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormGenerator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SelectedListItem
    {
        public int id { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> ListId { get; set; }
        public string Name { get; set; }
    
        public virtual SelectList SelectList { get; set; }
    }
}
