//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormGenerator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSubmission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserSubmission()
        {
            this.UserSubmissionValues = new HashSet<UserSubmissionValue>();
        }
    
        public long Id { get; set; }
        public System.DateTime SubmissionTime { get; set; }
        public int FormId { get; set; }
    
        public virtual Form Form { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserSubmissionValue> UserSubmissionValues { get; set; }
    }
}
